### ISSUE TITLE
Add flag to hide warnings

### ISSUE THREAD

**Issue by nantonel** [kul-optec/ProximalAlgorithms.jl#25] opened 2019-08-08 08:55 UTC
Should be easy to implement?

For example in [PANOC](https://github.com/kul-forbes/ProximalAlgorithms.jl/blob/f76fa06f026118ec2ad5685389dd144806ce54b5/src/algorithms/panoc.jl#L98)
```julia
if warnings
  @warn "parameter `gamma` became too small ($(state.gamma)), stopping the iterations"
end
```
I would also default it to `warnings=false`.

**Comment by lostella** [comment] 2019-08-12 11:55
I agree in principle, but could you attach a MWE that triggers the warning? Because while hiding the warning we should also (i) make sure that no bug is causing the line search to fail (ii) if no bug is there, make the algorithm's stopping criterion more robust (or line search one, or both).

**Comment by nantonel** [comment] 2019-08-24 09:31
Stumbled upon this MWE

```julia
using StructuredOptimization
using Random
using ProximalAlgorithms: PANOC 
using ProximalOperators, AbstractOperators
using RecursiveArrayTools

Random.seed!(13)
n,m = 10,20
Y = randn(n,m)

A = [Eye(size(Y)) Eye(size(Y))]
x0 = ArrayPartition(zeros(size(Y)), zeros(size(Y)))

f = PrecomposeDiagonal(SqrNormL2(), 1.0, Y)
g1 = NormL1() 
g2 = IndBallRank(2) 
g = SeparableSum(g2,g1) 

solver = PANOC(verbose=true)
solver(x0; f=f, A=A, g=g)
```
maybe there's something simpler but better then nothing for the moment!

**Comment by lostella** [comment] 2019-08-24 13:13
On Julia 1.1.1 I get an even stranger behaviour:

```
[...]
  120 | 4.750e-01 | 8.124e-08 | 1.000e+00
  130 | 4.750e-01 | 1.877e-07 | 5.000e-01
┌ Warning: stepsize `tau` became too small (0.0009765625), stopping the iterations
└ @ ProximalAlgorithms ~/.julia/dev/ProximalAlgorithms/src/algorithms/panoc.jl:182
  139 | 4.750e-01 | 7.043e-07 | 7.813e-03
  149 | 4.750e-01 | 1.803e-07 | 5.000e-01
[...]
```

i.e., the warning is actually a lie! (The iteration continues somehow) Looking into it.

**Comment by nantonel** [comment] 2019-08-24 14:04
Yes, I forgot to mention that I'm in Julia 1.1.1!

**Comment by lostella** [comment] 2019-08-24 15:37
Seems like a weird bug (and a hard one to reproduce): changing the last two lines in the MWE to

```julia
solver = PANOC(verbose=true, freq=1)
solver(x0; f=f, A=A, g=g)
```

then the iterations do stop as expected:

```
[...]
  135 | 4.750e-01 | 4.292e-08 | 1.000e+00
  136 | 4.750e-01 | 4.575e-08 | 1.000e+00
  137 | 4.750e-01 | 1.417e-08 | 1.250e-01
  138 | 4.750e-01 | 2.124e-07 | 1.250e-01
  139 | 4.750e-01 | 2.189e-07 | 7.813e-03
┌ Warning: stepsize `tau` became too small (0.0009765625), stopping the iterations
└ @ ProximalAlgorithms ~/.julia/dev/ProximalAlgorithms/src/algorithms/panoc.jl:182
julia> 
```

**Comment by nantonel** [comment] 2019-08-24 15:44
Very strange!! We should check in Julia 1.2.. but I'm not going to update yet (waiting next week)

**Comment by nantonel** [comment] 2019-11-18 09:23
Seems in the latest version the MWE below doesn't raise any warnings!
At least when using PANOC, ZeroFPR is still having some. 

> Stumbled upon this MWE
> 
> ```julia
> using StructuredOptimization
> using Random
> using ProximalAlgorithms: PANOC 
> using ProximalOperators, AbstractOperators
> using RecursiveArrayTools
> 
> Random.seed!(13)
> n,m = 10,20
> Y = randn(n,m)
> 
> A = [Eye(size(Y)) Eye(size(Y))]
> x0 = ArrayPartition(zeros(size(Y)), zeros(size(Y)))
> 
> f = PrecomposeDiagonal(SqrNormL2(), 1.0, Y)
> g1 = NormL1() 
> g2 = IndBallRank(2) 
> g = SeparableSum(g2,g1) 
> 
> solver = PANOC(verbose=true)
> solver(x0; f=f, A=A, g=g)
> ```
> 
> maybe there's something simpler but better then nothing for the moment!

**Comment by lostella** [comment] 2021-06-13 18:10
I’m closing this, since using `@warn` or other builtin logging utilities already allows tuning the logging level, see e.g. [disable_logging](https://docs.julialang.org/en/v1/stdlib/Logging/#Logging.disable_logging).

**Closed by lostella** 2021-06-13 18:10 UTC
